<a href="https://colab.research.google.com/github/Pelosomelo/Misp/blob/main/cd_podstaw_pythona.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#importowanie, numpy daje funkcje matlaba
import numpy as np

In [ ]:
a_list= [1,2,3,4,5, [1,2,3], "temat"] # nie idealna lista
k_krotka = (1,2,3,4,5, [1,2,3], "temat") #krotka nie można dorzucać więcej elementów 
b_list = [1,2,3,4,5]
n_array = np.array(b_list) # wektor numpy


In [ ]:
print(a_list+b_list)#połączenie list
print(n_array+n_array)# sómójemy wektory więc się dodadzą

[1, 2, 3, 4, 5, [1, 2, 3], 'temat', 1, 2, 3, 4, 5]
[ 2  4  6  8 10]


In [ ]:
a_list[3]

4

In [ ]:
a_list.append(100)
print(a_list)

[1, 2, 3, 4, 5, [1, 2, 3], 'temat', 100]


In [ ]:
k_krotka[4]

5

In [ ]:
k_krotka.append(100)

AttributeError: ignored

In [ ]:
np.array(b_list)+np.array(b_list)

array([ 2,  4,  6,  8, 10])

In [ ]:
n_array = np.array(a_list) # wektor numpy

In [ ]:
n_array

array([1, 2, 3, 4, 5, list([1, 2, 3]), 'temat'], dtype=object)

In [ ]:
#### Nowosci

studenci_slownik = {123: 123,"Igor":3, "Frankek":5, "Zosia":22,"Julia":[2,21], (1,2):"Krotka"}#nie wolno wstawić listy tu

In [ ]:
print(studenci_slownik)

{123: 123, 'Igor': 3, 'Frankek': 5, 'Zosia': 22, 'Julia': [2, 21], (1, 2): 'Krotka'}


In [ ]:
studenci_slownik["Zosia"]# pobieranie z slownika

22

In [ ]:
studenci_slownik["Drugi Franek"]= 3 #dopisywanie do slownika
print(studenci_slownik)

{123: 123, 'Igor': 3, 'Frankek': 5, 'Zosia': 22, 'Julia': [2, 21], (1, 2): 'Krotka', 'Drugi Franek': 3}


In [ ]:
# wyciąganie danych hurtem z slownika klucze
for elementy in studenci_slownik: 
    print(elementy)

# wyciąganie danych hurtem z slownika klucze
print("*"*20)
for elementy in studenci_slownik.keys():
    print(elementy)

123
Igor
Frankek
Zosia
Julia
(1, 2)
Drugi Franek
********************
123
Igor
Frankek
Zosia
Julia
(1, 2)
Drugi Franek


In [ ]:
# wyciąganie danych hurtem z slownika i klucze i wartości
for elementy in studenci_slownik.items():
    print(elementy)

# wyciąganie danych hurtem z slownika i klucze i wartości ale oddzielnie
print("*"*20)
for imie, ocena in studenci_slownik.items():
    print("{}ma ocene{}".format(imie,ocena))

(123, 123)
('Igor', 3)
('Frankek', 5)
('Zosia', 22)
('Julia', [2, 21])
((1, 2), 'Krotka')
('Drugi Franek', 3)
********************
123ma ocene123
Igorma ocene3
Frankekma ocene5
Zosiama ocene22
Juliama ocene[2, 21]
(1, 2)ma oceneKrotka
Drugi Franekma ocene3


In [ ]:
# wyciąganie danych hurtem z slownika wartości
for elementy in studenci_slownik.values():
    print(elementy)

123
3
5
22
[2, 21]
Krotka
3


In [ ]:
studenci_slownik["Cuthulu"]= -1000000

NameError: ignored

In [ ]:
studenci_slownik

{(1, 2): 'Krotka',
 123: 123,
 'Cuthulu': -1000000,
 'Drugi Franek': 3,
 'Frankek': 5,
 'Igor': 3,
 'Julia': [2, 21],
 'Zosia': 22}

In [ ]:
automatyczna_lista=[liczba**2 for liczba in range(100) if liczba%4==0]
print(automatyczna_lista)

automatyczna_lista_pary=[(liczba,liczba**2) for liczba in range(100) if liczba%4==0]
print(automatyczna_lista_pary)

[0, 16, 64, 144, 256, 400, 576, 784, 1024, 1296, 1600, 1936, 2304, 2704, 3136, 3600, 4096, 4624, 5184, 5776, 6400, 7056, 7744, 8464, 9216]
[(0, 0), (4, 16), (8, 64), (12, 144), (16, 256), (20, 400), (24, 576), (28, 784), (32, 1024), (36, 1296), (40, 1600), (44, 1936), (48, 2304), (52, 2704), (56, 3136), (60, 3600), (64, 4096), (68, 4624), (72, 5184), (76, 5776), (80, 6400), (84, 7056), (88, 7744), (92, 8464), (96, 9216)]


In [ ]:
stara_lista=["Igor","Pawel","nie_imie","Ania"]
#rospoznawanie imienia po durzych literach na początku 
nowa_lista=[imie for imie in stara_lista if imie[0].isupper()]
# można and dać przed ostatnim nawiasem ] i kolejny warunek 
print(nowa_lista)

['Igor', 'Pawel', 'Ania']


In [ ]:
#automattyczne tworzenie słownika z kluczy starego słownika
studenci = studenci_slownik.keys()
automatyczny_slownik=dict(para for para in enumerate(studenci))
print(automatyczny_slownik)

{0: 123, 1: 'Igor', 2: 'Frankek', 3: 'Zosia', 4: 'Julia', 5: (1, 2), 6: 'Drugi Franek', 7: 'Cuthulu'}


In [ ]:
# słowniki i zbiory durzo szybciej wyszukują informację niż tablice
print(studenci_slownik)

print("Igor" in studenci_slownik)

{123: 123, 'Igor': 3, 'Frankek': 5, 'Zosia': 22, 'Julia': [2, 21], (1, 2): 'Krotka', 'Drugi Franek': 3, 'Cuthulu': -1000000}
True


In [ ]:
##### zbiory są w stanie bardzo szybko powiedzieć czy cos jest w czymś innym

a={1,2,3,"Franek"}
b={2,3,4,"Franek"}


In [ ]:
a|b #suma zbiorów, sum of sets

{1, 2, 3, 4, 'Franek'}

In [ ]:
a.add("Franek")# dodawanie do zbioru 
print(a)

{1, 2, 3, 'Franek'}


In [ ]:
1 in a
"Igor" in studenci_slownik

True

In [ ]:
studenci_lista = ["Igor_model"+str(nr) for nr in range(1000)]
print(studenci_lista)
studenci_set= set(studenci_lista)
print(studenci_set)

#kasowanie powturzeń
powtarzajaca_lista=["Igor" for el in range(1000)]
print(powtarzajaca_lista)
print(set(powtarzajaca_lista))

['Igor_model0', 'Igor_model1', 'Igor_model2', 'Igor_model3', 'Igor_model4', 'Igor_model5', 'Igor_model6', 'Igor_model7', 'Igor_model8', 'Igor_model9', 'Igor_model10', 'Igor_model11', 'Igor_model12', 'Igor_model13', 'Igor_model14', 'Igor_model15', 'Igor_model16', 'Igor_model17', 'Igor_model18', 'Igor_model19', 'Igor_model20', 'Igor_model21', 'Igor_model22', 'Igor_model23', 'Igor_model24', 'Igor_model25', 'Igor_model26', 'Igor_model27', 'Igor_model28', 'Igor_model29', 'Igor_model30', 'Igor_model31', 'Igor_model32', 'Igor_model33', 'Igor_model34', 'Igor_model35', 'Igor_model36', 'Igor_model37', 'Igor_model38', 'Igor_model39', 'Igor_model40', 'Igor_model41', 'Igor_model42', 'Igor_model43', 'Igor_model44', 'Igor_model45', 'Igor_model46', 'Igor_model47', 'Igor_model48', 'Igor_model49', 'Igor_model50', 'Igor_model51', 'Igor_model52', 'Igor_model53', 'Igor_model54', 'Igor_model55', 'Igor_model56', 'Igor_model57', 'Igor_model58', 'Igor_model59', 'Igor_model60', 'Igor_model61', 'Igor_model62', '

### Własne typy

In [ ]:
zajecia = [["wf"],
           ["informatyka", "nauka czytania"],
           ["relax", "jedzenie"],
           ["mispy","mispy w domu"],
           ["piateczek", "praca domowa z mispow", "Ilovemispy", "mispy w czasie snu"]
          ]

dnityg= ["Pon","Wto","Sro","Czwar","Pio"]

def dodaj_dwie_liczby(liczba1,liczba2):
    return liczba1+liczba2

In [ ]:
class DzienZajec(): # tworzymy klase o nazwie dzień zajęć
    """obiekt trzymający dany dzień zajęć i przypisane mu metody"""
    
    
    def __init__(self, lista_na_dany_dzien, nazwa_dnia): #definicja ,self to odniesienie w tym przypadku do Dzien zajec czyli do nazwy klasy
        self.lista_zajec= lista_na_dany_dzien
        self.dzien = nazwa_dnia
        

    
    def ile_mispow(self):
        ile_m = sum([1 for zajecie in self.lista_zajec if "misp" in zajecie.lower()])
        return ile_m

    @property #zamienia na wlasciwosc   
    def ile_zajec(self):
        return len(self.lista_zajec)
    
    def __repr__(self):
        zajecia_do_stringa = ", ".join(self.lista_zajec)
        return "W dzien {} mam zajecia: {}".format(self.dzien, zajecia_do_stringa)
    

In [ ]:
pio_zajecia = DzienZajec(["piateczek", "praca domowa z mispow", "Ilovemispy", "mispy w czasie snu"],
                        "piatek")

In [ ]:
pio_zajecia.ile_zajec

4

In [ ]:
print(pio_zajecia)

W dzien piatek mam zajecia: piateczek, praca domowa z mispow, Ilovemispy, mispy w czasie snu


In [ ]:
pio_zajecia.lista_zajec

['piateczek', 'praca domowa z mispow', 'Ilovemispy', 'mispy w czasie snu']

In [ ]:
pio_zajecia.lista_zajec.append("MISP")
print(pio_zajecia.lista_zajec)

['piateczek', 'praca domowa z mispow', 'Ilovemispy', 'mispy w czasie snu', 'MISP']


In [ ]:
pio_zajecia.ile_mispow()

4

In [ ]:
print(pio_zajecia.lista_zajec)


['piateczek', 'praca domowa z mispow', 'Ilovemispy', 'mispy w czasie snu', 'MISP']


In [ ]:
pio_zajecia

W dzien piatek mam zajecia: piateczek, praca domowa z mispow, Ilovemispy, mispy w czasie snu, MISP

In [ ]:
print(pio_zajecia.ile_zajec)

5


In [ ]:
lista_zajec= [DzienZajec(lista_dzien, dzien) for lista_dzien, dzien in 
             zip(zajecia,dnityg)]

In [ ]:
print(lista_zajec)

[W dzien Pon mam zajecia: wf, W dzien Wto mam zajecia: informatyka, nauka czytania, W dzien Sro mam zajecia: relax, jedzenie, W dzien Czwar mam zajecia: mispy, mispy w domu, W dzien Pio mam zajecia: piateczek, praca domowa z mispow, Ilovemispy, mispy w czasie snu]


In [ ]:
posortowane_po_zajeciach=sorted(lista_zajec, key= lambda zajecie: zajecie.ile_zajec)
posortowane_po_mispach=sorted(lista_zajec, key= lambda zajecie: zajecie.ile_mispow())

In [ ]:
print(posortowane_po_zajeciach)

[W dzien Pon mam zajecia: wf, W dzien Wto mam zajecia: informatyka, nauka czytania, W dzien Sro mam zajecia: relax, jedzenie, W dzien Czwar mam zajecia: mispy, mispy w domu, W dzien Pio mam zajecia: piateczek, praca domowa z mispow, Ilovemispy, mispy w czasie snu]


In [ ]:
print(posortowane_po_mispach)

[W dzien Pon mam zajecia: wf, W dzien Wto mam zajecia: informatyka, nauka czytania, W dzien Sro mam zajecia: relax, jedzenie, W dzien Czwar mam zajecia: mispy, mispy w domu, W dzien Pio mam zajecia: piateczek, praca domowa z mispow, Ilovemispy, mispy w czasie snu]


##### challenge 1

Stworz typ NumerTelefonu

 -- przy tworzeniu sprawdza czy właściwy numer (Polski) jeśli nie pisze, że error (ew. Exception)
 
 -- gdy printuję to mi pisze polskimi słowami i.e. "jeden, pięć, siedem, zero"
 
 -- gdy wywołuję właściwość wojewodzwtwo, podaje mi wojewodztwo ew. ze to komorkowy
 
 

In [ ]:
# ma na takie rzeczy być w stanie odpowiedzieć
#typ i klasa numeru
class NumerTelefonu():

    def __init__(self, lista_numeru): 
        self.numer= lista_numeru
        

    def czy_prawidlowy_nr(self):
        if "4" in self.numer[0] !=0 and (len(self.numer))==9:
          print("prawidlowy numer")
        else:
          print("Błąd")
  
    def __repr__(self):
        a=[]
        for cyfra in self.numer:
          if cyfra == "1":
            a.append("jeden")
          elif cyfra == "2":
            a.append("dwa")
          elif cyfra == "3":
            a.append("trzy")
          elif cyfra == "4":
            a.append("cztery")
          elif cyfra == "5":
            a.append("pięć")
          elif cyfra == "6":
            a.append("sześć")
          elif cyfra == "7":
            a.append("siedem")
          elif cyfra == "8":
            a.append("osiem")
          elif cyfra == "9":
            a.append("dziewięć")
          else:
            a.append("zero") 
        return "{}".format(a)

    def wojewodztwo(self):
        if "4" in self.numer[0] and "2" in self.numer[1]:
          print("Łódź")
        else:
          print("inne woj")       

 




#>>> "prawidlowy numer"

#print("*"*20)

#numer_lodz.wojewodztwo 
#>>> "Lodz"

#print("*"*20)

#print(numer_lodz)
#>>> "cztery dwa sześć osiem siedem siedem osiem sześć osiem"

In [ ]:
numer_lodz = NumerTelefonu("426877868")
numer_lodz.czy_prawidlowy_nr()
print(numer_lodz)
numer_lodz.wojewodztwo() 

prawidlowy numer
['cztery', 'dwa', 'sześć', 'osiem', 'siedem', 'siedem', 'osiem', 'sześć', 'osiem']
Łódź
